name: Build SideBar
on: 
  repository_dispatch:
    types:
      - build-sidebar

jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '18.3.0'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install string-format
          node ./genDailyLog.js
