on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run the action on a test graph and publish
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build graph's SPA
          uses: logseq/publish-spa@main
          with:
            graph-directory: .
            theme-mode: light
            accent-color: blue

        - name: Add a nojekyll file # to make sure asset paths are correctly identified
          run: touch $GITHUB_WORKSPACE/www/.nojekyll

        - name: Inject Script
          run: sed -i "s@</body>@$( cat $GITHUB_WORKSPACE/logseq/inject.html | tr '\n' ' ' | sed 's@&@\\&@g' )</body>@"  $GITHUB_WORKSPACE/www/index.html

        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@v4
          with:
          folder: www

        # - name: Deploy
        #   uses: s0/git-publish-subdir-action@develop
        #   env:
        #       REPO: git@github.com:fishyer/MyLogseq-Public.git
        #       BRANCH: main
        #       FOLDER: www
        #       SSH_PRIVATE_KEY: ${{ secrets.MAC_PRIVATE_KEY }}